### ISSUE TITLE
cannot run second ingress controller via nginx-helm-operator

### ISSUE THREAD

**Issue by NICK0TIN** [nginxinc/nginx-ingress-helm-operator#497]
### Version

  app.kubernetes.io/version: 4.0.1
  helm.sdk.operatorframework.io/chart: nginx-ingress
  helm.sh/chart: nginx-ingress-2.0.1

### What Kubernetes platforms are you running on?

Openshift

### Steps to reproduce

Via the OpenShift operatorhub I try to create 2 or more NginxIngress object that will trigger the helm chart to deploy the Nginx controller.

 The 2nd controller I try to deploy fails, because the first SA "nginx-ingress" is created and managed by the first Helm chart.

I read that this can be configured by setting the values file:
```
controller:
  serviceAccount:
    ## Autogenerated if not set or set to "".
    name: nginx-ingress
```
However no matter the name given, the SA will always be created as nginx-ingress.

Steps to reproduce:

Create any NginxIngress on OpenShift and give a different name than nginx-ingress.

```
controller:
  serviceAccount:
    ## Autogenerated if not set or set to "".
    name: nginx-ingress-test
```

![Image](https://github.com/user-attachments/assets/4e322392-4aeb-4830-820f-497e89713c30)
![Image](https://github.com/user-attachments/assets/0354e3fb-72c4-47a1-91ae-36c6fc1b0aa1)
